services:
  app:
    build: .
    restart: always
    environment:
      MAILAROO_DATABASE_URL: postgres://${DB_USER:-mailaroo}:${DB_PASS:-mailaroo_pass}@db:5432/${DB_NAME:-mailaroo}?sslmode=disable
      MAILAROO_WEB_PORT: 8080
      MAILAROO_WEB_CSRF_SECURE: false
      MAILAROO_LOG_LEVEL: info
      MAILAROO_STORAGE_TYPE: local
      MAILAROO_LOCAL_STORAGE_BASE_PATH: /app/data/emails
    ports:
      - "8080:8080"
      - "25:25"
      - "2525:2525"
    volumes:
      - ./data:/app/data
    depends_on:
      migrate:
        condition: service_completed_successfully

  migrate:
    image: amacneil/dbmate
    environment:
      DATABASE_URL: postgres://${DB_USER:-mailaroo}:${DB_PASS:-mailaroo_pass}@db:5432/${DB_NAME:-mailaroo}?sslmode=disable
    volumes:
      - ./db/migrations:/db/migrations
    command: up
    depends_on:
      - db

  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-mailaroo}
      POSTGRES_PASSWORD: ${DB_PASS:-mailaroo_pass}
      POSTGRES_DB: ${DB_NAME:-mailaroo}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
